### ISSUE TITLE
Carousel ReWrite

### ISSUE THREAD

**Issue by timi95** [Eltee-Taiwo/ForceWielder#3]
Leye - "Carousel: Loop. Some weird stuff seems to happen with sizing."

Basically successfully replace or rebuild carousel.

**Comment by Eltee-Taiwo** [comment]
When scrolling through the carousel, the next item doesn't render right away.

![image](https://user-images.githubusercontent.com/37124491/88094926-f0297c80-cb59-11ea-85df-7588e44ee73c.png)
